#on: [push, pull_request]
on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        #go-version: [1.13.x, 1.14.x]
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -race ./...
      - name: Unit Test
        run: go test -race $(go list ./... | grep -v integration_tests)
      - name: Integration Test
        run: go test -race -v -p 1 ./integration_tests/...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICES_API_URL: ${{ secrets.outputs.SERVICES_API_URL_DEV }}
          VAULT_API_URL: ${{ secrets.VAULT_API_URL_DEV }}
          VAULT_SALT_SECRET: ${{ secrets.VAULT_SALT_SECRET_DEV }}
          SERVICES_HUB_AUTH_URL: ${{ secrets.SERVICES_HUB_AUTH_URL_DEV }}
          TXL_HUB_TARGET: ${{ secrets.TXL_HUB_TARGET_DEV }}
          TXL_HUB_MA: ${{ secrets.TXL_HUB_MA_DEV }}
          TXL_THREADS_TARGET: ${{ secrets.TXL_THREADS_TARGET_DEV }}
          TXL_HUB_GATEWAY_URL: ${{ secrets.TXL_HUB_GATEWAY_URL_DEV }}
          TXL_USER_KEY: ${{ secrets.TXL_USER_KEY_DEV }}
          TXL_USER_SECRET: ${{ secrets.TXL_USER_SECRET_DEV }}
          SPACE_STORAGE_SITE_URL: ${{ secrets.SPACE_STORAGE_SITE_URL_DEV }}